"""Works cited in the essay. Titles, years, venues and links come from the site's data (the references as the
AI manuscripts and papers list them); a few links were cleaned of LaTeX residue. Volumes and pages are given
only where the data or the publisher's DOI make them certain."""

REFS = {
 # ---- sources ----
 'openai_math': dict(type='misc', author=['OpenAI'], title='OpenAI Math Release: research manuscripts and Lean formalizations', year='2026',
                     url='https://github.com/openai/math', note='Apache 2.0; 722 manuscripts released 6 October 2026, 719 current after 7 October'),
 'openai_ns': dict(type='misc', author=['OpenAI'], title='Finite time blowup for Navier–Stokes', year='2026',
                   url='https://cdn.openai.com/pdf/32d9f210-8b73-45e0-91bc-82a30aef8a9a/navier-stokes.pdf',
                   note='Lean formalization: https://github.com/openai/NavierStokesAndEuler'),
 'jumper2021': dict(type='article', author=['John Jumper', 'others'], title='Highly accurate protein structure prediction with AlphaFold',
                    journal='Nature', year='2021', doi='10.1038/s41586-021-03819-2', volume='596', pages='583–589'),
 # ---- machine learning ----
 'deepseek2025': dict(type='misc', author=['DeepSeek-AI'], title='DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning',
                      year='2025', url='https://arxiv.org/abs/2501.12948'),
 'shumailov2024': dict(type='article', author=['Ilia Shumailov', 'others'], title='AI models collapse when trained on recursively generated data',
                       journal='Nature', volume='631', pages='755–759', year='2024', doi='10.1038/s41586-024-07566-y'),
 'mathlib2020': dict(type='inproceedings', author=['The mathlib Community'], title='The Lean mathematical library',
                     booktitle='Proceedings of the 9th ACM SIGPLAN International Conference on Certified Programs and Proofs (CPP 2020)',
                     year='2020', doi='10.1145/3372885.3373824', pages='367–381'),
 # ---- machine learning: training and reinforcement learning ----
 'brown2020': dict(type='misc', author=['Tom B. Brown', 'others'], title='Language Models are Few-Shot Learners', year='2020', url='https://arxiv.org/abs/2005.14165'),
 'shannon1948': dict(type='article', author=['Claude E. Shannon'], title='A Mathematical Theory of Communication', journal='Bell System Technical Journal',
                     volume='27', pages='379–423', year='1948', doi='10.1002/j.1538-7305.1948.tb01338.x'),
 'deletang2024': dict(type='misc', author=['Grégoire Delétang', 'others'], title='Language Modeling Is Compression', year='2023', url='https://arxiv.org/abs/2309.10668'),
 'ouyang2022': dict(type='misc', author=['Long Ouyang', 'others'], title='Training language models to follow instructions with human feedback', year='2022', url='https://arxiv.org/abs/2203.02155'),
 'lewkowycz2022': dict(type='misc', author=['Aitor Lewkowycz', 'others'], title='Solving Quantitative Reasoning Problems with Language Models', year='2022', url='https://arxiv.org/abs/2206.14858'),
 'gunasekar2023': dict(type='misc', author=['Suriya Gunasekar', 'others'], title='Textbooks Are All You Need', year='2023', url='https://arxiv.org/abs/2306.11644'),
 'shao2024': dict(type='misc', author=['Zhihong Shao', 'others'], title='DeepSeekMath: Pushing the Limits of Mathematical Reasoning in Open Language Models', year='2024', url='https://arxiv.org/abs/2402.03300'),
 'zelikman2022': dict(type='misc', author=['Eric Zelikman', 'others'], title='STaR: Bootstrapping Reasoning With Reasoning', year='2022', url='https://arxiv.org/abs/2203.14465'),
 'yue2025': dict(type='misc', author=['Yang Yue', 'others'], title='Does Reinforcement Learning Really Incentivize Reasoning Capacity in LLMs Beyond the Base Model?', year='2025', url='https://arxiv.org/abs/2504.13837'),
 'amodei2016': dict(type='misc', author=['Dario Amodei', 'others'], title='Concrete Problems in AI Safety', year='2016', url='https://arxiv.org/abs/1606.06565'),
 'skalse2022': dict(type='misc', author=['Joar Skalse', 'others'], title='Defining and Characterizing Reward Hacking', year='2022', url='https://arxiv.org/abs/2209.13085'),
 'snell2024': dict(type='misc', author=['Charlie Snell', 'others'], title='Scaling LLM Test-Time Compute Optimally can be More Effective than Scaling Model Parameters', year='2024', url='https://arxiv.org/abs/2408.03314'),
 'wang2022sc': dict(type='misc', author=['Xuezhi Wang', 'others'], title='Self-Consistency Improves Chain of Thought Reasoning in Language Models', year='2022', url='https://arxiv.org/abs/2203.11171'),
 'lightman2023': dict(type='misc', author=['Hunter Lightman', 'others'], title='Let’s Verify Step by Step', year='2023', url='https://arxiv.org/abs/2305.20050'),
 'yao2022': dict(type='misc', author=['Shunyu Yao', 'others'], title='ReAct: Synergizing Reasoning and Acting in Language Models', year='2022', url='https://arxiv.org/abs/2210.03629'),
 # ---- mathematics cited by the AI manuscripts ----
 'grothendieck1957': dict(type='article', author=['Alexander Grothendieck'], title='Sur la classification des fibrés holomorphes sur la sphère de Riemann',
                          journal='American Journal of Mathematics', year='1957', doi='10.2307/2372388', volume='79', pages='121'),
 'renwang2025': dict(type='misc', author=['Kevin Ren', 'Hong Wang'], title='Furstenberg sets estimate in the plane', year='2025',
                     url='https://arxiv.org/abs/2308.08819'),
 'guthwangzhang2020': dict(type='article', author=['Larry Guth', 'Hong Wang', 'Ruixiang Zhang'], title='A sharp square function estimate for the cone in R³',
                           journal='Annals of Mathematics', year='2020', doi='10.4007/annals.2020.192.2.6', volume='192', pages='551–581'),
 'farguesscholze2024': dict(type='misc', author=['Laurent Fargues', 'Peter Scholze'], title='Geometrization of the local Langlands correspondence',
                            year='2024', url='https://arxiv.org/abs/2102.13459'),
 'birkar2019': dict(type='article', author=['Caucher Birkar'], title='Anti-pluricanonical systems on Fano varieties', journal='Annals of Mathematics',
                    year='2019', doi='10.4007/annals.2019.190.2.1', volume='190', pages='345–463'),
 'dashaconpaun2024': dict(type='misc', author=['Omprokash Das', 'Christopher D. Hacon', 'Mihai Păun'],
                          title='On the 4-dimensional minimal model program for Kähler varieties', year='2024', url='https://arxiv.org/abs/2205.12205'),
 'dchn2011': dict(type='article', author=['Hugo Duminil-Copin', 'Clément Hongler', 'Pierre Nolin'],
                  title='Connection probabilities and RSW-type bounds for the two-dimensional FK Ising model',
                  journal='Communications on Pure and Applied Mathematics', year='2011', doi='10.1002/cpa.20370', volume='64', pages='1165–1198'),
 'dms2021': dict(type='article', author=['Bertrand Duplantier', 'Jason Miller', 'Scott Sheffield'], title='Liouville quantum gravity as a mating of trees',
                 journal='Astérisque', volume='427', year='2021', doi='10.24033/ast.1149'),
 'lovaszszegedy2006': dict(type='article', author=['László Lovász', 'Balázs Szegedy'], title='Limits of dense graph sequences',
                           journal='Journal of Combinatorial Theory, Series B', year='2006', doi='10.1016/j.jctb.2006.05.002', volume='96', pages='933–957'),
 'bkt2004': dict(type='article', author=['Jean Bourgain', 'Nets Hawk Katz', 'Terence Tao'], title='A sum-product estimate in finite fields, and applications',
                 journal='Geometric and Functional Analysis', year='2004', doi='10.1007/s00039-004-0451-1', volume='14', pages='27–57'),
 'talagrand2011': dict(type='book', author=['Michel Talagrand'], title='Mean Field Models for Spin Glasses. Volume I: Basic Examples',
                       publisher='Springer', year='2011', doi='10.1007/978-3-642-15202-3'),
 'perelman2002': dict(type='misc', author=['Grigori Perelman'], title='The entropy formula for the Ricci flow and its geometric applications',
                      year='2002', url='https://arxiv.org/abs/math/0211159'),
 'deligne1982': dict(type='incollection', author=['Pierre Deligne'], title='Hodge cycles on abelian varieties (notes by J. S. Milne)',
                     booktitle='Hodge Cycles, Motives, and Shimura Varieties', series='Lecture Notes in Mathematics', volume='900',
                     publisher='Springer', year='1982', url='https://www.jmilne.org/math/Documents/Deligne82_2003.pdf'),
 'besicovitch1928': dict(type='article', author=['A. S. Besicovitch'], title='On Kakeya’s problem and a similar one', journal='Mathematische Zeitschrift',
                         year='1928', doi='10.1007/BF01171101', volume='27', pages='312–320'),
 'davies1971': dict(type='article', author=['Roy O. Davies'], title='Some remarks on the Kakeya problem', journal='Proceedings of the Cambridge Philosophical Society',
                    year='1971', doi='10.1017/S0305004100046867', volume='69', pages='417–421'),
 'wolff1995': dict(type='article', author=['Thomas Wolff'], title='An improved bound for Kakeya type maximal functions',
                   journal='Revista Matemática Iberoamericana', year='1995', doi='10.4171/RMI/188', volume='11', pages='651–674'),
 'klt2000': dict(type='article', author=['Nets Hawk Katz', 'Izabella Łaba', 'Terence Tao'], title='An improved bound on the Minkowski dimension of Besicovitch sets in R³',
                 journal='Annals of Mathematics', year='2000', doi='10.2307/2661389', volume='152', pages='383'),
 'bct2006': dict(type='article', author=['Jonathan Bennett', 'Anthony Carbery', 'Terence Tao'], title='On the multilinear restriction and Kakeya conjectures',
                 journal='Acta Mathematica', year='2006', doi='10.1007/s11511-006-0006-4', volume='196', pages='261–302'),
 'guth2010': dict(type='article', author=['Larry Guth'], title='The endpoint case of the Bennett–Carbery–Tao multilinear Kakeya conjecture',
                  journal='Acta Mathematica', year='2010', doi='10.1007/s11511-010-0055-6', volume='205', pages='263–286'),
 'wangzahl2025': dict(type='misc', author=['Hong Wang', 'Joshua Zahl'], title='Volume estimates for unions of convex sets, and the Kakeya set conjecture in three dimensions',
                      year='2025', url='https://arxiv.org/abs/2502.17655'),
 'wangzahl2026': dict(type='article', author=['Hong Wang', 'Joshua Zahl'], title='Sticky Kakeya sets and the sticky Kakeya conjecture',
                      journal='Journal of the American Mathematical Society', year='2026', doi='10.1090/jams/1067', volume='39', pages='515–585'),
 'gowwz2025': dict(type='article', author=['Shaoming Guo', 'Changkeun Oh', 'Hong Wang', 'Shukun Wu', 'Ruixiang Zhang'],
                   title='The Bochner–Riesz problem: an old approach revisited', journal='Peking Mathematical Journal', year='2025', doi='10.1007/s42543-023-00082-4', volume='8', pages='201–270'),
 'tao2003': dict(type='article', author=['Terence Tao'], title='A sharp bilinear restriction estimate for paraboloids', journal='Geometric and Functional Analysis',
                 year='2003', doi='10.1007/s00039-003-0449-0', volume='13', pages='1359–1384'),
 'xuzhang2019': dict(type='article', author=['Chenyang Xu', 'Lei Zhang'], title='Nonvanishing for 3-folds in characteristic p>5', journal='Duke Mathematical Journal',
                     year='2019', doi='10.1215/00127094-2018-0066', volume='168', pages='1269–1301'),
 'denghanima2025': dict(type='misc', author=['Yu Deng', 'Zaher Hani', 'Xiao Ma'], title='Long time derivation of the Boltzmann equation from hard sphere dynamics',
                        year='2025', url='https://arxiv.org/abs/2408.07818'),
 'yau1978': dict(type='article', author=['Shing-Tung Yau'], title='On the Ricci curvature of a compact Kähler manifold and the complex Monge–Ampère equation. I',
                 journal='Communications on Pure and Applied Mathematics', year='1978', doi='10.1002/cpa.3160310304', volume='31', pages='339–411'),
 'yau1994': dict(type='misc', author=['Shing-Tung Yau'], title='Open problems in geometry', year='1994'),
 'erdos1957': dict(type='article', author=['Paul Erdős'], title='Some unsolved problems', journal='Michigan Mathematical Journal', year='1957',
                   doi='10.1307/mmj/1028997963', volume='4'),
 'descartes1637': dict(type='book', author=['René Descartes'], title='La Géométrie', note='appendix to the Discours de la méthode', year='1637'),
 'riemann1859': dict(type='article', author=['Bernhard Riemann'], title='Ueber die Anzahl der Primzahlen unter einer gegebenen Grösse',
                     journal='Monatsberichte der Berliner Akademie', year='1859', url='https://www.maths.tcd.ie/pub/HistMath/People/Riemann/Zeta/'),
 'morgantian2007': dict(type='book', author=['John W. Morgan', 'Gang Tian'], title='Ricci Flow and the Poincaré Conjecture',
                        publisher='American Mathematical Society and Clay Mathematics Institute', year='2007',
                        url='https://www.claymath.org/library/monographs/cmim03.pdf'),
 'dingslysun2022': dict(type='article', author=['Jian Ding', 'Allan Sly', 'Nike Sun'], title='Proof of the satisfiability conjecture for large k',
                        journal='Annals of Mathematics', year='2022', doi='10.4007/annals.2022.196.1.1', volume='196', pages='1–388'),
 'leehuangyang1957': dict(type='article', author=['T. D. Lee', 'Kerson Huang', 'C. N. Yang'],
                          title='Eigenvalues and eigenfunctions of a Bose system of hard spheres and its low-temperature properties',
                          journal='Physical Review', year='1957', doi='10.1103/PhysRev.106.1135', volume='106', pages='1135–1145'),
 # ---- fluid equations and protein structure ----
 'euler1757': dict(type='article', author=['Leonhard Euler'], title='Principes généraux du mouvement des fluides',
                   journal='Mémoires de l’Académie des sciences de Berlin', year='1757', url='https://scholarlycommons.pacific.edu/euler-works/226/'),
 'leray1934': dict(type='article', author=['Jean Leray'], title='Sur le mouvement d’un liquide visqueux emplissant l’espace', journal='Acta Mathematica',
                   year='1934', doi='10.1007/BF02547354', volume='63', pages='193–248'),
 'ckn1982': dict(type='article', author=['Luis Caffarelli', 'Robert Kohn', 'Louis Nirenberg'],
                 title='Partial regularity of suitable weak solutions of the Navier–Stokes equations',
                 journal='Communications on Pure and Applied Mathematics', year='1982', doi='10.1002/cpa.3160350604', volume='35', pages='771–831'),
 'fefferman2000': dict(type='misc', author=['Charles L. Fefferman'], title='Existence and smoothness of the Navier–Stokes equation',
                       howpublished='Clay Mathematics Institute, Millennium Prize Problem statement', year='2000',
                       url='https://www.claymath.org/wp-content/uploads/2022/06/navierstokes.pdf'),
 'anfinsen1973': dict(type='article', author=['Christian B. Anfinsen'], title='Principles that govern the folding of protein chains', journal='Science',
                      year='1973', doi='10.1126/science.181.4096.223', volume='181', pages='223–230'),
}
